### PR TITLE
added additional params for list expansion, paging

### PR DESCRIPTION
**Pull request by joelvarty**

### CODE REVIEW

**Comment by joelvarty** [comment]
@joshua-isaac This is something that was requested by a partner, but it will also make life a lot better for any devs using it.  Let me know when you get a chance to review.  Some test cases were added.

**Review by alitahir360 — APPROVED** [review]
the two tests that are omitted will need to be added back again once fixed.

**Comment by joelvarty** [comment]
> the two tests that are omitted will need to be added back again once fixed.

Done!

**Comment by jamesvidler** [comment]
Looks good! I created a couple "todo" issues on the repo for future updates to make

**Pull request merged**
